### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by thetarnav** [lawrencecchen/sailwind#1]
[sailwind.dev](https://sailwind.dev/) is not working :(

![image](https://user-images.githubusercontent.com/24491503/197514801-335f0023-8c16-47b1-8e2c-c56cdf13bea2.png)

**Comment by lawrencecchen** [comment]
Ah yes, was running low on railway credits. Will set up something free on replit.

**Comment by lawrencecchen** [comment]
Up and running now: https://sailwind.dev
